---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.20.0
  - name: containers.podman
    version: 1.14.0
  - name: fedora.linux_system_roles
    version: 1.78.2

roles: []
