---
keycloak_exposed_port: 443
keycloak_admin_username: "admin"
keycloak_admin_password: "admin"

# Get values from Postgres vars
keycloak_postgres_username: "{{ hostvars[groups['postgres'][0]]['postgres_username'] }}"
keycloak_postgres_password: "{{ hostvars[groups['postgres'][0]]['postgres_password'] }}"
keycloak_postgres_database: "{{ hostvars[groups['postgres'][0]]['postgres_database'] }}"

keycloak_podman_secrets:
  - name: "keycloak-admin-credentials"
    data: |
      apiVersion: v1
      data:
        username: "{{ keycloak_admin_username | b64encode }}"
        password: "{{ keycloak_admin_password | b64encode }}"
      kind: Secret
      metadata:
        name: keycloak-admin-credentials
    skip_existing: true
  - name: "postgres-credentials"
    data: |
      apiVersion: v1
      data:
        username: "{{ keycloak_postgres_username | b64encode }}"
        password: "{{ keycloak_postgres_password | b64encode }}"
      kind: Secret
      metadata:
        name: postgres-credentials
    skip_existing: true
keycloak_podman_kube_specs:
  - state: "started"
    kube_file_content:
      apiVersion: "v1"
      kind: "Pod"
      metadata:
        name: "keycloak"
      spec:
        containers:
          - name: "keycloak"
            image: "quay.io/keycloak/keycloak:24.0"
            ports:
              - containerPort: 8443
                hostPort: "{{ keycloak_exposed_port }}"
            args:
              - "start"
            env:
              - name: "KEYCLOAK_ADMIN"
                valueFrom:
                  secretKeyRef:
                    name: "keycloak-admin-credentials"
                    key: "username"
              - name: "KEYCLOAK_ADMIN_PASSWORD"
                valueFrom:
                  secretKeyRef:
                    name: "keycloak-admin-credentials"
                    key: "password"
              - name: "KC_DB"
                value: "postgres"
              # - name: "KC_DB_URL"
              #   value: "jdbc:postgresql://postgres1.lab.vagrant:5432/{{ keycloak_postgres_database }}"
              - name: "KC_DB_URL_HOST"
                value: "{{ hostvars[groups['postgres'][0]]['postgres_master_fqdn'] }}" # Get values from Postgres vars
              - name: "KC_DB_URL_PORT"
                value: "{{ hostvars[groups['postgres'][0]]['postgres_exposed_port'] }}" # Get values from Postgres vars
              - name: "KC_DB_URL_DATABASE"
                value: "{{ keycloak_postgres_database }}"
              - name: "KC_DB_USERNAME"
                valueFrom:
                  secretKeyRef:
                    name: "postgres-credentials"
                    key: "username"
              - name: "KC_DB_PASSWORD"
                valueFrom:
                  secretKeyRef:
                    name: "postgres-credentials"
                    key: "password"
              - name: "KC_HOSTNAME_URL"
                value: "https://{{ ansible_hostname }}.{{ ansible_dns.search[0] }}{{(':' + keycloak_exposed_port) if (keycloak_exposed_port != 443)}}"
              - name: "KC_HTTPS_CERTIFICATE_KEY_FILE"
                value: "/etc/pki/tls/keycloak/selfsigned.key"
              - name: "KC_HTTPS_CERTIFICATE_FILE"
                value: "/etc/pki/tls/keycloak/selfsigned.pem"
              # - name: "KC_HTTPS_CLIENT_AUTH"
              #   value: "required"
              - name: "JAVA_OPTS_APPEND"
                value: "-Djava.net.preferIPv4Stack=true" # Disables IPv6
            volumeMounts:
              - name: "certificate-volume"
                mountPath: "/etc/pki/tls/keycloak:z"
                readOnly: true
        volumes:
          - name: "certificate-volume"
            hostPath:
              path: "/home/{{ podman_run_as_user }}/certs"

keycloak_common:
  keycloak_url: "https://keycloak1.lab.vagrant"
  realm: "master"
  username: "{{ keycloak_admin_username }}"
  password: "{{ keycloak_admin_password }}"
  validate_certs: false # Remove in prod
keycloak_realms:
  - realm: "ldap"
keycloak_user_federations:
  - realm: "ldap"
    name: "ldap"
    provider_id: "ldap"
    authType: "simple"
    bindCredential: "{{ openldap_readonly_password }}"
    bindDn: "cn={{ openldap_readonly_username }},dc={{ ansible_dns.search[0] | split('.') | join(',dc=') }}"
    connectionUrl: "ldap://openldap.dns.podman"
    rdnLDAPAttribute: "uid"
    syncRegistrations: true
    userObjectClasses: "inetOrgPerson"
    usernameLDAPAttribute: "uid"
    usersDn: "ou=People,dc={{ ansible_dns.search[0] | split('.') | join(',dc=') }}"
    uuidLDAPAttribute: "uid"
keycloak_clients:
  - realm: "ldap"
    id: "example-client"
    base_url: "http://example.lab.vagrant"
    redirect_uris:
      - "http://example.lab.vagrant/*"
    secret: "abcdefghijklmnopqrstuvwxyz123456"
